repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
  - repo: local
    hooks:
      - id: test
        name: test
        entry: make test
        language: system